plugins {
    id 'java-library'
    id 'com.google.protobuf' version '0.9.4'
}

dependencies {
    api 'com.fasterxml.jackson.core:jackson-annotations'
    api 'com.fasterxml.jackson.core:jackson-databind'
    api 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
    api 'io.opentelemetry:opentelemetry-api'
    compileOnly 'org.jetbrains:annotations'

    api platform('io.grpc:grpc-bom:1.75.0')
    api 'io.grpc:grpc-stub'
    api 'io.grpc:grpc-protobuf'
    api 'com.google.protobuf:protobuf-java:3.25.5'
    implementation 'javax.annotation:javax.annotation-api:1.3.2'
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.25.5'
    }
    plugins {
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.75.0'
        }
    }
    generateProtoTasks {
        all().configureEach {
            plugins {
                grpc {}
            }
        }
    }
}

sourceSets {
    main {
        java {
            srcDirs 'build/generated/source/proto/main/grpc'
            srcDirs 'build/generated/source/proto/main/java'
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    dependsOn 'generateProto'
}
